name: Deploy to docker hub and quay.io

on:
   push:
     branches:    
      - master
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Image Name
        id: image_name
        run: echo "##[set-output name=image;]$(echo $GITHUB_REPOSITORY:$IMAGE_TAG)"

      - name: Build image
        if: success()
        run: docker build -t ${GITHUB_REPOSITORY}:${IMAGE_TAG} .

      - name: Test image
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          image: ${{ steps.image_name.outputs.image }}
          configFile: container-structure-test.yaml

      - name: Publish to dockerhub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:${IMAGE_TAG}
      
      - name: Docker Hub Description
        if: success() 
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: jbangdev/jbang-action

      - name: Login to Quay.io
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY_URL: quay.io

      - name: Build/tag image for Quay.io
        if: success()
        run: docker build -t quay.io/jbangdev/jbang-action:${IMAGE_TAG} .

      - name: Publish to Quay.io
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push quay.io/jbangdev/jbang-action:${IMAGE_TAG}

      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-
    
      - name: Update quay.io Description
        uses: maxandersen/jbang-action@v3.1
        with:
          script: .github/workflows/updatequay.java
          args: "--token $TOKEN"
        env:
          TOKEN: ${{ secrets.QUAY_TOKEN }}
      