name: Deploy to docker hub and quay.io

on:
   push:
     branches:    
      - master
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Image Name
        id: image_name
        run: echo "##[set-output name=image;]$(echo $GITHUB_REPOSITORY:$IMAGE_TAG)"

      - name: Override tag for master
        if: github.ref == 'ref/head/master'
        run: ::set-env name=IMAGE_TAG::master

      - name: Build image
        if: success()
        run: docker build -t ${GITHUB_REPOSITORY}:${IMAGE_TAG} -t quay.io/jbangdev/jbang-action:${IMAGE_TAG} .

      - name: Tag latest if v-release
        if: success() && startsWith(github.ref, 'refs/tags/v')
        run: docker build -t ${GITHUB_REPOSITORY}:latest -t quay.io/jbangdev/jbang-action:latest .

      - name: Test image
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          image: ${{ steps.image_name.outputs.image }}
          configFile: container-structure-test.yaml

      - name: Publish to dockerhub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}

      - name: Docker Hub Description
        if: success()
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: jbangdev/jbang-action

      - name: Login to Quay.io
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY_URL: quay.io


      - name: Publish to Quay.io
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push quay.io/jbangdev/jbang-action

      - name: Update quay.io Description
        if: success()
        uses: maxandersen/jbang-action@v3.1
        with:
          script: .github/workflows/updatequay.java
          args: "--token $TOKEN"
        env:
          TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Github Release
        if:  success() && startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          body: "See https://github.com/jbangdev/jbang/releases/tag/${IMAGE_TAG}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-
