# This is a basic workflow to help you get started with Actions

name: verify-githubaction

on:
  workflow_dispatch:
  schedule:
  - cron:  '* */8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: properties@jbangdev
      uses: jbangdev/jbang-action@v0.39.0
      with:
        script: properties@jbangdev
